// using constant to avoid typos
export const LOAD_COURSES_SUCCES = 'LOAD_COURSES_SUCCES';
export const LOAD_AUTHORS_SUCCES = 'LOAD_AUTHORS_SUCCES';
export const CREATE_COURSE_SUCCES = 'CREATE_COURSE_SUCCES';
export const UPDATE_COURSE_SUCCES = 'UPDATE_COURSE_SUCCES';
